### ISSUE TITLE
Error connecting to target: TLS Cannot be established

### ISSUE THREAD

**Issue by motoko-ayanami** [Moopinger/smugglefuzz#2]
I'm running this against the request smuggling labs on hackthebox, but they don't have https properly setup. Is there a way to bypass this error message? 
![error message](https://github.com/Moopinger/smugglefuzz/assets/122310140/d04976fb-50ca-444e-9312-6a107b2ab425)

**Comment by Moopinger** [comment]
Hi, thanks for trying out SmuggleFuzz, i appreciate it. For more info see here: https://github.com/Moopinger/smugglefuzz/tree/experimental-h2c
