### ISSUE TITLE
No url displayed in batch scan

### ISSUE THREAD

**Issue by Aarui920511** [Moopinger/smugglefuzz#3]
No url displayed in batch scan，Halfway through the scan, an http smuggling vulnerability was discovered, but I couldn’t tell which URL it was from.Hope to add scanning information corresponding to the URL

**Comment by Moopinger** [comment]
Thanks for reporting i will look into this

**Comment by Aarui920511** [comment]
I'm very sorry. It was my mistake. I didn't look carefully. The URL was displayed in the batch scan.

**Comment by Moopinger** [comment]
No worries, thanks for letting me know, if anything else comes up please let me know! All the best
