### ISSUE TITLE
adding response match e.g. specific string in response

### ISSUE THREAD

**Issue by 0xAwali** [Moopinger/smugglefuzz#5]
while reading this https://portswigger.net/research/trace-desync-attack it will be good to add response matching e.g. --filter 'specific string in response'

**Comment by Moopinger** [comment]
Hi there, thanks for the suggestion. I have added this feature in 0.2.2 https://github.com/Moopinger/smugglefuzz/releases You can now specify the keyword flag (-k) and the response will contain "Keyword: True" if the keyword present in the response body. You can include the filter for this ("Keyword: True") to only include responses with the keyword. ./smugglefuzz scan -u https://localhost:8443 -k Flag9009 --filter "Keyword: True" -e

Cheers!

**Comment by 0xAwali** [comment]
thank you :)
